# Site settings
title: Hope's Horse Therapy
subtitle: Helping Horses - One Horse at a Time
email: janet@hopeshorsetherapy.com
description: >-
  Dedicated to improving the lives of horses by releasing tension and increasing 
  their range of motion through one-on-one bodywork. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hopeshorsetherapy.com"

email_username: janet@hopeshorsetherapy.com
twitter_username:
facebook_username: HopesHorseTherapy
instagram_username: hopeshorsetherapy 
youtube_username: "@HopesHorseTherapy"
your_name: Janet & Hobbes # Your Name for About
about_yourself: "Duis interdum tincidunt risus. Integer a pellentesque nulla, ut tempus nunc. Mauris sed tortor vitae leo ullamcorper suscipit. Donec dignissim sollicitudin rutrum. Nam eleifend fermentum neque, a dictum velit. Nullam malesuada, nulla a dapibus efficitur, metus tortor sodales dui, eu luctus urna eros nec ipsum. Suspendisse id neque tristique, efficitur orci ut, blandit libero. Curabitur pellentesque condimentum ipsum, sed fermentum diam dictum ac. Curabitur eu aliquam neque, eu vulputate ipsum. Aliquam erat volutpat."
copyright_name: Hope's Horse Therapy

# Build settings
theme: null

plugins:
  - jekyll-feed
  - jekyll-paginate

markdown: kramdown
paginate: 5

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - README.md
  - tmp/
